### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Suston** [Adamekka/whenthe#2]
Dear Developer,

I hope you're doing well. Would you consider sucking the dick of the individual mentioned below, if given the opportunity?

Thank you for your response.

Best regards,
Suston
![0f427dfe-3ce5-4788-acce-824a485925a5](https://github.com/user-attachments/assets/0f7d1b5c-a31d-461b-847d-2aec3f57e266)

**Comment by Adamekka** [comment]
Hello Suston,

Yes.

Thank you for your understanding.

**Comment by kokssik** [comment]
> Hello Suston,
> 
> Yes.
> 
> Thank you for your understanding.

Čus pičus,

Same.

Thank me for my understanding.
